### ISSUE TITLE
Broken link to knitted HTML of 'Building co-expression networks, associations with traits and GO'

### ISSUE THREAD

**Issue by LNGDingj** [jackhump/ALS_SpinalCord_QTLs#1]
Hello Jack @jackhump 

There is a broken link to knitted HTML of 'Building co-expression networks, associations with traits and GO' at 
https://github.com/jackhump/ALS_SpinalCord_QTLs#co-expression-networks
![image](https://github.com/jackhump/ALS_SpinalCord_QTLs/assets/53267778/a3b338b1-102b-4c8b-95b5-c3c4c293da61)

Could you help to re-link the html with 'Building co-expression networks, associations with traits and GO'? I am interested in reading it.  Thanks a lot!

**Comment by jackhump** [comment]
Hello! I've just uploaded the HTML for the co-expression analysis and fixed the link in the README. It usually takes < 1 hour or so for github to update HTML pages. Let me know by tomorrow if you still can't view it. Otherwise you can just download the HTML file from the html/ folder and view it in your browser.

**Comment by LNGDingj** [comment]
Great! Thanks so much!
